title: DROID Docs
description: Developer documentation for recreating the DROID platform setup.
theme: just-the-docs

url: https://droid-dataset.github.io/droid # this url not being used right now
color_scheme: droid # TODO: update name to DROID

aux_links:
  Official GitHub Repository: https://github.com/droid-dataset/droid
